### PR TITLE
Handle rejected promises correctly

### LINKED ISSUE #24: !card: Handle a broken Gatherer page correctly
When Gatherer is down, using !card will cause an UnhandledPromiseRejectionWarning in Discord.js that locks the bot from taking further commands. Needs to be investigated.

### PR DESCRIPTION
**Pull request by hgarus**
Fixes #24

Various discord.js methods return promises, return these from various
modules and write a log entry on rejection.

Switch to request-promise-native to make returning promises from the
modules using request easier.

In cards handle downloading the gatherer image manually instead of relying
on discords fileresolver, this allows us to differentiate an image
download error from an error that occurs while sending the discord
message, which enables us to fall back on sending a message without an
image.

### CODE REVIEW

**Review by bra1n — CHANGES_REQUESTED** [review]
I like the rewrite, but I would still use message.sendFile over pulling the card image manually here. A fix for the rejected promise in sendFile (discord.js) is being worked on here: https://github.com/hydrabolt/discord.js/pull/886

File: modules/card.js [hunk 1]
```diff
@@ -60,10 +60,19 @@ class MtgCardLoader {
                     response += "\n\n:arrow_right: Other matching cards: :large_blue_diamond:" + otherCardNames.join(" :large_blue_diamond:");
                 }
                 if (card.imageUrl) {
-                    msg.channel.sendFile(card.imageUrl, _.snakeCase(_.deburr(card.name)) + ".jpg", response);
```
Comment (bra1n) [inline modules/card.js:63]: Will be fixed with https://github.com/hydrabolt/discord.js/pull/886

Comment (hgarus) [reply modules/card.js:63]: I would like to keep it this way until, a new version of discord.js is released which handles the problem.

With the current version of discord.js card search would be non-functional while gatherer is down.

Comment (bra1n) [reply modules/card.js:63]: Fair point.

**Review by bra1n — APPROVED** [review]
